FROM grafana/grafana:latest

COPY grafana/provisioning/datasources/prometheus.dev.yml /etc/grafana/provisioning/datasources/prometheus.yml
COPY grafana/provisioning/dashboards /etc/grafana/provisioning/dashboards
COPY grafana/dashboards /etc/grafana/provisioning/dashboards
